import { useEffect, useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Alert, Image } from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { openControllerDoor } from '@/lib/api';
import * as Speech from 'expo-speech';

export default function EntryNoCodeApprovalScreen() {
  const router = useRouter();
  const params = useLocalSearchParams();
  
  const [requestId] = useState(String(params.requestId || ''));
  const [visitorName] = useState(String(params.visitorName || ''));
  const [areaName] = useState(String(params.areaName || ''));
  const [sectorName] = useState(String(params.sectorName || ''));
  const [qrCode, setQrCode] = useState<string>('');
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);

  useEffect(() => {
    generateQRCode();
    speakApprovalMessage();
  }, []);

  const generateQRCode = () => {
    // Generate QR code for approved visit
    // This would typically come from the API response
    const qrData = JSON.stringify({
      requestId: requestId,
      visitorName: visitorName,
      areaName: areaName,
      sectorName: sectorName,
      timestamp: new Date().toISOString(),
      type: 'TEMPORARY_VISIT'
    });
    
    // For now, create a mock QR code data
    // In production, this should be generated by the backend
    setQrCode(btoa(qrData));
  };

  const speakApprovalMessage = async () => {
    setIsSpeaking(true);
    const options = {
      language: 'es',
      pitch: 1.0,
      rate: 0.8,
      volume: 0.8,
    };
    
    try {
      await Speech.speak('Visita aprobada, capture foto de QR', options);
    } catch (error) {
      console.log('❌ Speech error:', error);
    } finally {
      setIsSpeaking(false);
    }
  };

  const handleProceed = async () => {
    if (isProcessing) return;

    try {
      setIsProcessing(true);
      
      console.log('🚪 Opening door for approved visitor...');
      await openControllerDoor();
      
      Alert.alert('Éxito', 'Puerta abierta correctamente');
      
      // Navigate back to home
      router.replace('/home');
      
    } catch (err) {
      console.log('❌ Error opening door:', err);
      Alert.alert(
        'Error', 
        err instanceof Error ? err.message : 'No se pudo abrir la puerta'
      );
    } finally {
      setIsProcessing(false);
    }
  };

  const handleBack = () => {
    router.replace('/home');
  };

  // Mock QR code display - in production, use a QR code library
  const renderQRCode = () => {
    if (!qrCode) return null;
    
    // For now, show a placeholder
    // In production, integrate a QR code library like react-native-qrcode-svg
    return (
      <View style={styles.qrPlaceholder}>
        <Text style={styles.qrPlaceholderText}>QR CODE</Text>
        <Text style={styles.qrSubText}>{visitorName}</Text>
        <Text style={styles.qrSubText}>{areaName} - {sectorName}</Text>
      </View>
    );
  };

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={handleBack}>
          <Text style={styles.back}>Atrás</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Visita Aprobada</Text>
        <View style={{ width: 60 }} />
      </View>

      <View style={styles.content}>
        <View style={styles.approvalContainer}>
          <Text style={styles.approvalTitle}>✅ Visita Aprobada</Text>
          
          {/* QR Code Section */}
          <View style={styles.qrSection}>
            <Text style={styles.qrInstruction}>Tome Foto de QR</Text>
            
            <View style={styles.qrContainer}>
              {renderQRCode()}
            </View>
            
            <Text style={styles.qrNote}>
              Muestre este código QR para ingresar
            </Text>
          </View>

          {/* Visitor Details */}
          <View style={styles.detailsContainer}>
            <Text style={styles.detailsTitle}>Datos del Visitante</Text>
            
            <View style={styles.detailItem}>
              <Text style={styles.detailLabel}>Nombre:</Text>
              <Text style={styles.detailValue}>{visitorName}</Text>
            </View>
            
            <View style={styles.detailItem}>
              <Text style={styles.detailLabel}>Destino:</Text>
              <Text style={styles.detailValue}>{areaName} - {sectorName}</Text>
            </View>
          </View>

          {/* Status Indicator */}
          <View style={styles.statusContainer}>
            <Text style={styles.statusText}>
              {isSpeaking ? '🔊 Hablando...' : '✅ Listo para ingresar'}
            </Text>
          </View>
        </View>

        {/* Action Button */}
        <View style={styles.buttonContainer}>
          <TouchableOpacity 
            style={[
              styles.proceedButton,
              isProcessing && styles.disabledButton
            ]}
            onPress={handleProceed}
            disabled={isProcessing}
          >
            <Text style={styles.proceedButtonText}>
              {isProcessing ? 'Abriendo puerta...' : 'Proceder a Ingresar'}
            </Text>
          </TouchableOpacity>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    height: 64,
    paddingHorizontal: 16,
    paddingTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#16A34A',
  },
  back: {
    color: '#fff',
    fontWeight: '800',
    width: 60,
    fontSize: 16,
  },
  headerTitle: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 18,
  },
  content: {
    flex: 1,
    padding: 20,
  },
  approvalContainer: {
    flex: 1,
    alignItems: 'center',
  },
  approvalTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#16A34A',
    marginBottom: 24,
    textAlign: 'center',
  },
  qrSection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  qrInstruction: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1E3A8A',
    marginBottom: 16,
    textAlign: 'center',
  },
  qrContainer: {
    width: 200,
    height: 200,
    backgroundColor: '#fff',
    borderWidth: 3,
    borderColor: '#16A34A',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  qrPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrPlaceholderText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1E3A8A',
    marginBottom: 8,
  },
  qrSubText: {
    fontSize: 12,
    color: '#64748B',
    textAlign: 'center',
  },
  qrNote: {
    fontSize: 14,
    color: '#64748B',
    textAlign: 'center',
    fontWeight: '600',
  },
  detailsContainer: {
    width: '100%',
    backgroundColor: '#F0FDF4',
    borderRadius: 12,
    padding: 20,
    marginBottom: 24,
  },
  detailsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#16A34A',
    marginBottom: 16,
    textAlign: 'center',
  },
  detailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  detailLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#64748B',
  },
  detailValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
    flex: 1,
    textAlign: 'right',
  },
  statusContainer: {
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 16,
  },
  statusText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#16A34A',
    textAlign: 'center',
  },
  buttonContainer: {
    paddingBottom: 20,
  },
  proceedButton: {
    backgroundColor: '#16A34A',
    borderRadius: 12,
    padding: 18,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  disabledButton: {
    backgroundColor: '#94A3B8',
    shadowOpacity: 0,
    elevation: 0,
  },
  proceedButtonText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 18,
  },
});
